const fs = require('fs');
const file = 'src/app/(main)/about/page.js';
let content = fs.readFileSync(file, 'utf8');
content = content.replace(/Pune's/g, 'Pune&apos;s')
  .replace(/EUS's/g, 'EUS&apos;s')
  .replace(/don't/g, 'don&apos;t')
  .replace(/let's/g, 'let&apos;s')
  .replace(/We've/g, 'We&apos;ve')
  .replace(/we've/g, 'we&apos;ve')
  .replace(/haven't/g, 'haven&apos;t')
  .replace(/It's/g, 'It&apos;s')
  .replace(/you're/g, 'you&apos;re')
  .replace(/doesn't/g, 'doesn&apos;t')
  .replace(/won't/g, 'won&apos;t')
  .replace(/there's/g, 'there&apos;s')
  .replace(/that's/g, 'that&apos;s')
  .replace(/they're/g, 'they&apos;re')
  .replace(/we're/g, 'we&apos;re')
  .replace(/we'll/g, 'we&apos;ll')
  .replace(/you'll/g, 'you&apos;ll')
  .replace(/I'll/g, 'I&apos;ll')
  .replace(/who's/g, 'who&apos;s')
  .replace(/what's/g, 'what&apos;s')
  .replace(/developer's/g, 'developer&apos;s')
  .replace(/buyer's/g, 'buyer&apos;s')
  .replace(/builder's/g, 'builder&apos;s')
  .replace(/Pune’s/g, 'Pune&apos;s')
  .replace(/<a href="\/properties/g, '<Link href="/properties')
  .replace(/<\/a>/g, '</Link>')
  .replace(/"100B"/g, '&quot;100B&quot;')
  .replace(/"Smart"/g, '&quot;Smart&quot;')
  .replace(/"A-Grade"/g, '&quot;A-Grade&quot;')
  .replace(/"Zero Brokerage"/g, '&quot;Zero Brokerage&quot;')
  .replace(/"Golden"/g, '&quot;Golden&quot;')
  .replace(/"Diamond"/g, '&quot;Diamond&quot;');
fs.writeFileSync(file, content);
